# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b1a7e138952978bb10d841fae0b73aba0dd3e10b8229e26512211f9ab52922dbeb7a32e5048b6e072c3a5739b8c982548f7e6321ef0650decb4f474984e8136

test:
  secret_key_base: 9fa77a0863f99a85c0485df6a99f27a1a004ff8effd8c01ef4a4b496aeec3af01c181e77ed267ebad0720a67fc776d69471b496e1ad7af0f440e7ead2a155d9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
